### ISSUE TITLE
Analyse GPS_SERVO.ino

### ISSUE THREAD

**Issue by TheOneHyer** [SLSTP-2018/shab#1]
Comb over reference_code/GPS_SERVO.ino to identify useful code segments and techniques for our project.

**Comment by anna-sophia01** [comment]
Input is GPS based using a different Servo, so not a very useful reference code

**Comment by anna-sophia01** [comment]
see more recent reference code for useful notes etc

**Comment by TheOneHyer** [comment]
Closed as mostly irrelevant to our project as per @anna-sophia01's assessment.
