### ISSUE TITLE
Collect Manuals

### ISSUE THREAD

**Issue by TheOneHyer** [SLSTP-2018/shab#2]
Place all project-relevant manuals for Arduino and flight hardware in manuals folder.

**Comment by TheOneHyer** [comment]
Added Acrylic Chemical Resistance documentation in 7fc0713.

**Comment by TheOneHyer** [comment]
Replaced chemical resistance documentation in c0da744. The new sheet is much more detailed and covers temperature and far more chemicals than the previous sheet.

Based on this document, silicone oil will cause some damage to acrylic after seven days of constant exposure. Silicone grease will thus cause damage far slower. Ethanol and isopropyl alcohol will cause damage almost instantly to acrylic. Sodium hypochlorite has no noticeable impact on acrylic after 30 days of constant exposure.

**Comment by TheOneHyer** [comment]
Added MicroTrak AIO Manual in ff2b6ca.

**Comment by TheOneHyer** [comment]
LBNL ABCD Operating manual added in 14ce84a.

**Comment by TheOneHyer** [comment]
OSEPP Uno R3 Schematic added in 4ba922c.

**Comment by TheOneHyer** [comment]
Altimeter Module MS5607 Datasheet uploaded in fb53de0.

**Comment by TheOneHyer** [comment]
Altimeter Module MS5607 code examples added in e19a5f3.

**Comment by TheOneHyer** [comment]
Altimeter Module MS5607 demonstrations added in f636731.

**Comment by TheOneHyer** [comment]
Theory and Application of altimeters from Parallax, Inc. added in 0437e72.

**Comment by TheOneHyer** [comment]
Altimeter Module MS5607 added in 00032d8.

**Comment by TheOneHyer** [comment]
@andrewjong @tristcar @KaixinCui Could you guys check that I haven't missed any documentation in the [manuals folder](https://github.com/SLSTP-2018/shab/tree/master/manuals). Once we have all the documents we can close this issue.

**Comment by andrewjong** [comment]
Acknowledged. On it. ETA 3pm

**Comment by TheOneHyer** [comment]
Actuonix Linear Actuator manual added in 5fdbdcb. Thanks @andrewjong for noticing that this manual was missing.
